### ISSUE TITLE
Invalid sbom json

### ISSUE THREAD

**Issue by ObraztsovOleg** [CycloneDX/cyclonedx-cli#363] opened 2024-04-16 08:57 UTC
When I merge two sboms:
1. sbom.json
`{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:5c3bf41b-655c-47e1-9a10-867f270bb393",
  "version": 1,
  "metadata": {
    "timestamp": "2024-04-16T08:41:32.770Z",
    "tools": [
      {
        "vendor": "cyclonedx",
        "name": "cdxgen",
        "version": "8.6.2"
      }
    ],
    "authors": [
      {
        "name": "Prabhu Subramanian",
        "email": "prabhu@appthreat.com"
      }
    ]
  },
  "components": [],
  "services": [],
  "dependencies": []
}`

2. sbom.json
`{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:af178b8a-e4a8-47f7-b36f-40b789da47b8",
  "version": 1,
  "metadata": {
    "timestamp": "2024-04-16T08:41:32.770Z",
    "tools": [
      {
        "vendor": "cyclonedx",
        "name": "cdxgen",
        "version": "8.6.2"
      }
    ],
    "authors": [
      {
        "name": "Prabhu Subramanian",
        "email": "prabhu@appthreat.com"
      }
    ]
  },
  "components": [],
  "services": [],
  "dependencies": []
}`

I got invalid output sbom.json:
`{
  "bomFormat": "CycloneDX",
  "specVersion": "1.5",
  "serialNumber": "urn:uuid:ba2b30f1-be8f-44c9-aa02-fc53f28c2a1f",
  "version": 1,
  "metadata": {
    "tools": [
      {
        "vendor": "cyclonedx",
        "name": "cdxgen",
        "version": "8.6.2"
      }
    ],
    "component": {
      "type": "application",
      "group": "sbt_PROD.CI90000027_digs",
      "name": "digs",
      "version": "5.21.4-1416"
    }
  },
  "components": [],
  "services": [],
  "dependencies": []
}ncies": []
}`

**Comment by ertl** [comment] 2024-04-19 08:48
+1

**Comment by andreas-hilti** [comment] 2024-05-18 15:11
@ObraztsovOleg Could it be that the sbom.json existed and you tried to overwrite it?
If this is the case, then it would be a duplicate of https://github.com/CycloneDX/cyclonedx-cli/issues/255.

**Comment by mtsfoni** [comment] 2024-05-31 08:23
` "dependencies": [] }ncies": [] }`

Looks strongly like #255. 

If you still encounter the issue in the newest version, please feel free to reopen this issue or create a new one.

**Closed by mtsfoni** 2024-05-31 08:23 UTC
