### ISSUE TITLE
When I Upload this BOM Ver 1.5 it is not getting parse in Depedency-track V 4.9.1

### ISSUE THREAD

**Issue by Linish2020** [CycloneDX/cyclonedx-cli#351] opened 2023-11-30 13:34 UTC
[Cyclonedx (1).json](https://github.com/CycloneDX/cyclonedx-cli/files/13513416/Cyclonedx.1.json)

When I upload this Cyclone dx bom in dependency track server V4.9.1 it is getting failed as per Dependency-track team Null is not allowing to parse file on dependency-track server

**Comment by andreas-hilti** [comment] 2023-12-10 17:08
@Linish2020 I think if you replace on line 10
```"type": "null",```
by
```"type": "application",```
it should be fixed.

I believe the root cause is that here:
https://github.com/CycloneDX/cyclonedx-cli/blob/1034f85e5a757944de460cb843be3fd653bb2116/src/cyclonedx/Commands/Add/AddFilesCommand.cs#L58-L62
a line
```Type = Component.Classification.Application,```
is missing.

**Closed** 2024-05-11 20:42 UTC
